remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: dennistreysas Blog
description: A blog where I write about development stuff, mostly about the progress with my project 'railblocks'
show_downloads: false

